services:
  openwebui:
    container_name: openwebui
    image: ghcr.io/open-webui/open-webui:latest  # We'll configure specific version later
    restart: unless-stopped
    ports:
      - "${OPENWEBUI_PORT}:${OPENWEBUI_PORT}"
    environment:
      - HOST=${OPENWEBUI_HOST}
      - PORT=${OPENWEBUI_PORT}
      - TZ=${TZ}
    volumes:
      - ./docker/openwebui:/app/config        # Config directory
      - ./docker/openwebui/openwebui_data:/app/backend/data      # Add persistent volume for data
    networks:
      - openwebui_network

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      - TUNNEL_URL=http://openwebui:${OPENWEBUI_PORT}  # Use environment variable for port
    networks:
      - openwebui_network

networks:
  openwebui_network:
    name: openwebui_network
    driver: bridge

volumes:
  openwebui_data:  # Define the named volume for OpenWebUI data persistence 